# Generated by Django 4.0.7 on 2022-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_collection_nftport_unsupported"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
