# Generated by Django 4.0.7 on 2022-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_wallet_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="custom_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="wallet_custom_thumbnails/"
            ),
        ),
    ]
