# Generated by Django 4.0.7 on 2022-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_discorduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="username",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
