# Generated by Django 4.0.7 on 2022-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_discorduser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertrackedwallet",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
