# Generated by Django 4.0.8 on 2022-12-15 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_collection_community_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
