# Generated by Django 4.0.8 on 2023-01-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_walletnft_nft can only belong to one wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletnft",
            name="nft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.nft",
            ),
        ),
    ]
