# Generated by Django 4.0.8 on 2023-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_discorduser_is_beta_tester"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="access_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
