# Generated by Django 4.0.8 on 2023-02-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_discorduser_access_token_discorduser_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='mint_price_eth',
        ),
        migrations.AddField(
            model_name='collection',
            name='mint_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
