# Generated by Django 4.0.8 on 2023-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_collection_mint_price_eth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mint_price_eth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
