# Generated by Django 4.0.8 on 2023-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_collection_mint_price_eth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='mint_price_eth',
        ),
        migrations.AlterField(
            model_name='collection',
            name='supply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
